### ISSUE TITLE
Unable to retrieve byte-ranges from media playlist after retrieving segments

### ISSUE THREAD

**Issue by lucasweb78** [Comcast/hlsparserj#1]
The following exception is thrown when attempting to retrieve byte-ranges from a media playlist after retrieving segments:

java.lang.ClassCastException: com.comcast.viper.hlsparserj.tags.media.ExtInf cannot be cast to com.comcast.viper.hlsparserj.tags.media.ByteRange

**Comment by vipercoder** [comment]
Hi lucasweb78 - thanks for reporting the issue (and providing patches to resolve them).  Quickly glanced and seems to be good.  Will review them in detail and merge them in the next week or so.  Thanks again!

**Comment by vipercoder** [comment]
Thanks; merged.
