### ISSUE TITLE
Make available on Maven Central

### ISSUE THREAD

**Issue by lucasweb78** [Comcast/hlsparserj#4]
It would be great if the artifacts were available via Maven Central. Also are there any plans to move the project version 1.0.0 instead of a SNAPSHOT?

**Comment by lucasweb78** [comment]
Does anyone have any feedback on this?

**Comment by vipercoder** [comment]
Hi lucasweb78 - let me check internally and get back to you soon.  Thanks.

**Comment by vipercoder** [comment]
Hi lucasweb78 - thanks for your patience, finally got this deployed to maven central a few minutes ago.  Was able to link a project with this maven dependency clause:

<dependency>
  <groupId>com.comcast</groupId>
  <artifactId>hlsparserj</artifactId>
  <version>1.0.0</version>
</dependency>

Thanks.  Let me know if you see other issues!

**Comment by lucasweb78** [comment]
Many thanks for deploying this to Maven Central and for developing the library it has proved very useful.
